//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string RFC { get; set; }
    }
}
